name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
      
    - name: Build and test backend
      run: |
        cd backend
        chmod +x ./gradlew
        ./gradlew clean build
        
    - name: Build and test frontend
      run: |
        cd frontend
        npm install
        npm run build
        npm run test

    - name: Build and start containers
      run: |
        docker-compose build
        docker-compose up -d
        
    - name: Run integration tests
      run: |
        docker-compose run backend ./gradlew integrationTest

    - name: Stop containers
      run: docker-compose down
