name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
      
    - name: Build and test backend
      run: |
        chmod +x ./gradlew
        ./gradlew clean build
      working-directory: ./backend
        
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: npm install
      working-directory: '/home/runner/work/CRM/frontend/crm-project'

    - name: Run tests
      run: npm run test:headless
      working-directory: ./frontend

    - name: Build
      run: npm run build:prod
      working-directory: ./frontend

    - name: Build and start containers
      run: |
        docker-compose build
        docker-compose up -d
        
    - name: Run integration tests
      run: |
        docker-compose run backend ./gradlew integrationTest

    - name: Stop containers
      run: docker-compose down
